[1주차] 최승원 미션 제출합니다.
CEOS-Developers/react-profile-11th pull request #5
Opened 2020-04-03 13:06 UTC by seungwon2

이번 개발을 하면서 리액트, 자바스크립트에서 까먹은 부분, 헷갈리는 부분이 많아서 다시 제대로 공부해야겠다는 생각이 많이 들었습니다.
그리고 commit을 나눠서 하는 것을 잊어버리고 그냥 쭉 진행해버렸습니다 0.ㅠ
다음부터는 제대로 단계별로 나누어 commit하도록 하겠습니다!

https://react-profile-11th-tawny.now.sh/

2020-04-03 13:56 UTC, greatSumini requested changes
안녕하세요! 리뷰어 최수민입니다.
css flex 개념 활용해서 컴포넌트 구조 정말 잘 나눠주셨네요! 첫 미션인데 너무 잘 구현해주셔서 놀랐습니다 🥇 
리뷰 반영해서 작업하던 브랜치에 그대로 커밋해주시면 PR에 자동으로 쌓입니다!
수고하셨습니다 😃

2020-04-03 13:56 UTC, greatSumini commented on pages/index.js
>  import styled from 'styled-components';
import문을 작성하실 때, 비슷한 종류의 파일들끼리 묶어서 작성하시면 좋아요.
```
import React from 'react';
import styled from 'styled-components';

import ProfileCard from '../src/components/profile-card';
```
이렇게 외부 패키지는 위쪽에, 직접 작성한 컴포넌트는 아래쪽에 모아서 작성해주시면 보기 깔끔하고 좋습니다 😄

2020-04-03 13:56 UTC, greatSumini commented on pages/index.js
> +      </CardArea>
CardArea네이밍 좋네요 👍  몇가지 수정해주시면 더 좋을 것 같습니다!

1. Info라는 함수 이름은 `profile 배열을 받아서, 여러개의 ProfileCard를 반환한다`라는 역할을 충분히 표현하지 못 하는 것 같아요. `getProfileCardList` 같은 이름은 어떨까요?

2. `single`이라는 prop name은 `한 사람의 프로필 정보`라는 느낌이 들지 않는 것 같아요. `profile` 같은 이름은 어떨까요?

2. map처럼 간단한 함수인 경우 return문 안에 그대로 써주셔도됩니다!

```suggestion
      <CardArea>
       {profiles.map(profile =>
         <ProfileCard profile={profile}/>
       )}
      </CardArea>
```

2020-04-03 13:56 UTC, greatSumini commented on pages/index.js
> +  -webkit-box-pack: justify;
box-pack은 표준 문법이 아닙니다! [참고링크](https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack)
최신 IE와 firefox에서 지원되지 않습니다 ㅠㅠ [참고링크](https://caniuse.com/#search=box-pack)
사용 지양해주세요~

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +    <ImageContents>
indentation이 적용되지 않았네요 😢 prettier 설치 추천드립니다! 귀찮은 코드 포맷팅(들여쓰기, 띄어쓰기, 콤마, 등등)을 자동으로 해줘서 정말 편해요 :) [설치방법](https://analogcoding.tistory.com/164)

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +    display: block;
display 기본값이 block이기 때문에 따로 설정하지 않으셔도 됩니다!

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +    <Ceos> 신촌 연합 IT 창업 동아리 CEOS</Ceos>
`Ceos`라는 이름은 `동아리 이름을 보여준다`는 컴포넌트 역할을 충분히 설명하지 못 하고 있는 것 같아요.
또 범용성도 좋지 않구요. (나중에 `이화여자대학교 멋쟁이사자처럼`으로 문구가 바뀐다면 컴포넌트 이름도 `EwhaLikeLion`으로 바뀌어야겠죠?)
`ClubName` 같은 이름은 어떨까요?

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +          <UnivInfo>{props.single.univ}대학교 {props.single.major}과</UnivInfo>
`props.single.`이 여러번 반복되고 있네요. Javascript ES6의 destructuring을 사용해서 중복을 없앨 수 있습니다. [참고링크](https://javascript.info/destructuring-assignment)

return문 위에서 `const { name, age, role, univ, major } = props.single;` 같이 선언해주면 자동으로 props.single이 각 변수들에 분해/할당되기 때문에 
return문 안에서 name, age, role, univ, major라고만 써줘도 돼요!

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +`
img태그를 스타일링할때, div를 거치지 않고 바로 styled-components를 적용할 수 있습니다!
```suggestion
const Image = styled.img`
    width: 40%;
    height: 40%;
`
```

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +const Name = styled.div`
Name은 텍스트를 표현하는 컴포넌트니까 div 대신 p 태그를 사용하시는게 좋을 것 같아요!
```suggestion
const Name = styled.p`
```

2020-04-03 13:56 UTC, greatSumini commented on src/components/profile-card.js
> +const img = styled.div`
Component의 이름은 무조건 PascalCase(첫글자가 대문자인 camelCase)로 작성해주셔야합니다! [참고링크](https://www.quora.com/Why-do-React-components-use-PascalCase-for-filenames)

2020-04-04 02:10 UTC, greatSumini reviewed
추가 리뷰입니다 🤠

2020-04-04 02:10 UTC, greatSumini commented on src/components/profile-card.js
> +const Git = styled.div`
div 대신 a 태그 쓸 수 있어요!
```suggestion
const Git = styled.a`
```

2020-04-04 02:10 UTC, greatSumini commented on src/components/profile-card.js
> +    border-radius: 1.5rem;
코드 라인을 최대한 줄여주시는게 좋아요!
```suggestion
    border: 1px solid rgb(204, 204, 204);
    border-radius: 1.5rem;
```

2020-04-05 12:00 UTC, seungwon2 commented on src/components/profile-card.js
> +`
이 코드의 경우
img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
라는 에러가 떠서 img로 바꾸지 못했습니다 0.ㅠ

2020-04-06 07:07 UTC, greatSumini approved these changes

2020-04-06 07:07 UTC, merged